import { ProblemModel} from './problem.model';
import { TeamModel } from './team.model';

// Optional values are generated by Mongoose or MongoDB

export interface TestCaseSubmissionModel {
  hidden: boolean;
  input: string;
  output: string;
  correctOutput: string;
  correct?: boolean;
}

export interface DisputeModel {
  open: boolean;
  message: string;
}

interface BaseSubmissionModel {
  _id?: string;
  team: TeamModel;
  problem: ProblemModel;
  language: string;
  code: string;
  result?: string;
  test: boolean;
  points?: number;
  overrideCorrect?: boolean;
  datetime?: Date;
  dispute?: DisputeModel;
}

interface ErrorSubmissionModel extends BaseSubmissionModel {
  error?: string;
}

interface SuccessSubmissionModel extends BaseSubmissionModel {
  testCases?: TestCaseSubmissionModel[];
}

export interface SubmissionModel extends ErrorSubmissionModel, SuccessSubmissionModel {}