import { ProblemModel} from './problem.model';

// Optional values are generated by Mongoose or MongoDB

export interface TestCaseSubmissionModel {
  id: number;
  hidden: boolean;
  input: string;
  output: string;
  correctOutput: string;
  correct?: boolean;
}

interface BaseSubmissionModel {
  _id?: string;
  problem: ProblemModel;
  language: string;
  code: string;
  result?: string;
  test: boolean;
  points?: number;
  overrideCorrect?: boolean;
}

interface ErrorSubmissionModel extends BaseSubmissionModel {
  error?: string;
}

interface SuccessSubmissionModel extends BaseSubmissionModel {
  testCases?: TestCaseSubmissionModel[];
}

export interface SubmissionModel extends ErrorSubmissionModel, SuccessSubmissionModel {}